language: python
python:
 - "2.6"
 - "2.7"
env:
 - DJANGO_VERSION=1.3.4
 - DJANGO_VERSION=1.4.2
install:
 - pip install -qe git+https://github.com/django/django.git@${DJANGO_VERSION}#egg=Django
 - pip install -q -r travis.txt --use-mirrors
script: fab test
